name: CD

on:
  push:
    branches: [main]

env:
  NODE_VERSION: 18.x

jobs:
  bump-version:
    name: Bump package.json Versions
    if: ${{ !startsWith(github.event.head_commit.message, '[CI/CD]') }}
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.lib-bump.outputs.newTag }}

    steps:
      - uses: actions/checkout@v4
        with:
          # This is a fine-grained Github personal access token
          # for resource owner "politie" (needs admin approval)
          # and only repository "politie/ngx-sherlock"
          # with the following "Repository permissions":
          # - "Contents" (Access: Read and write),
          # - "Metadata" (Access: Read-only, this is mandatory).
          token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

      - name: Bump dev-app version
        id: dev-bump
        uses: phips28/gh-action-bump-version@v11.0.4
        with:
          tag-prefix: "v"
          skip-tag: true
          commit-message: "[CI/CD]: bump dev-app to {{version}}"

      - name: Bump lib version
        id: lib-bump
        uses: phips28/gh-action-bump-version@v11.0.4
        with:
          tag-prefix: "v"
          commit-message: "[CI/CD]: bump lib to {{version}}"
        env:
          PACKAGEJSON_DIR: projects/politie/ngx-sherlock

  github-release:
    name: Release on Github
    needs: bump-version
    if: startsWith(needs.bump-version.outputs.tag-name, 'v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump-version.outputs.tag-name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.bump-version.outputs.tag-name }}

  npm-release:
    name: Release on NPM
    needs: bump-version
    if: startsWith(needs.bump-version.outputs.tag-name, 'v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump-version.outputs.tag-name }}

      - name: Use node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Add token to .npmrc
        env:
          # This is a granular NPM access token
          # with "Packages and scopes" permission (Access: Read and write)
          # for the "@politie/ngx-sherlock" package only.
          npmToken: ${{ secrets.WORKFLOW_NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=$npmToken" >> .npmrc

      - name: Release
        run: npm publish ./dist/politie/ngx-sherlock
