import { List } from 'immutable';

export const redHeadedLeague = List([
    `ADVENTURE II. THE RED-HEADED LEAGUE`,
    ``,
    `I had called upon my friend, Mr. Sherlock Holmes, one day in the`,
    `autumn of last year and found him in deep conversation with a`,
    `very stout, florid-faced, elderly gentleman with fiery red hair.`,
    `With an apology for my intrusion, I was about to withdraw when`,
    `Holmes pulled me abruptly into the room and closed the door`,
    `behind me.`,
    ``,
    `"You could not possibly have come at a better time, my dear`,
    `Watson," he said cordially.`,
    ``,
    `"I was afraid that you were engaged."`,
    ``,
    `"So I am. Very much so."`,
    ``,
    `"Then I can wait in the next room."`,
    ``,
    `"Not at all. This gentleman, Mr. Wilson, has been my partner and`,
    `helper in many of my most successful cases, and I have no`,
    `doubt that he will be of the utmost use to me in yours also."`,
    ``,
    `The stout gentleman half rose from his chair and gave a bob of`,
    `greeting, with a quick little questioning glance from his small`,
    `fat-encircled eyes.`,
    ``,
    `"Try the settee," said Holmes, relapsing into his armchair and`,
    `putting his fingertips together, as was his custom when in`,
    `judicial moods. "I know, my dear Watson, that you share my love`,
    `of all that is bizarre and outside the conventions and humdrum`,
    `routine of everyday life. You have shown your relish for it by`,
    `the enthusiasm which has prompted you to chronicle, and, if you`,
    `will excuse my saying so, somewhat to embellish so many of my own`,
    `little adventures."`,
    ``,
    `"Your cases have indeed been of the greatest interest to me," I`,
    `observed.`,
    ``,
    `"You will remember that I remarked the other day, just before we`,
    `went into the very simple problem presented by Miss Mary`,
    `Sutherland, that for strange effects and extraordinary`,
    `combinations we must go to life itself, which is always far more`,
    `daring than any effort of the imagination."`,
    ``,
    `"A proposition which I took the liberty of doubting."`,
    ``,
    `"You did, Doctor, but none the less you must come round to my`,
    `view, for otherwise I shall keep on piling fact upon fact on you`,
    `until your reason breaks down under them and acknowledges me to`,
    `be right. Now, Mr. Jabez Wilson here has been good enough to call`,
    `upon me this morning, and to begin a narrative which promises to`,
    `be one of the most singular which I have listened to for some`,
    `time. You have heard me remark that the strangest and most unique`,
    `things are very often connected not with the larger but with the`,
    `smaller crimes, and occasionally, indeed, where there is room for`,
    `doubt whether any positive crime has been committed. As far as I`,
    `have heard it is impossible for me to say whether the present`,
    `case is an instance of crime or not, but the course of events is`,
    `certainly among the most singular that I have ever listened to.`,
    `Perhaps, Mr. Wilson, you would have the great kindness to`,
    `recommence your narrative. I ask you not merely because my friend`,
    `Dr. Watson has not heard the opening part but also because the`,
    `peculiar nature of the story makes me anxious to have every`,
    `possible detail from your lips. As a rule, when I have heard some`,
    `slight indication of the course of events, I am able to guide`,
    `myself by the thousands of other similar cases which occur to my`,
    `memory. In the present instance I am forced to admit that the`,
    `facts are, to the best of my belief, unique."`,
    ``,
    `The portly client puffed out his chest with an appearance of some`,
    `little pride and pulled a dirty and wrinkled newspaper from the`,
    `inside pocket of his greatcoat. As he glanced down the`,
    `advertisement column, with his head thrust forward and the paper`,
    `flattened out upon his knee, I took a good look at the man and`,
    `endeavoured, after the fashion of my companion, to read the`,
    `indications which might be presented by his dress or appearance.`,
    ``,
    `I did not gain very much, however, by my inspection. Our visitor`,
    `bore every mark of being an average commonplace British`,
    `tradesman, obese, pompous, and slow. He wore rather baggy grey`,
    `shepherd's check trousers, a not over-clean black frock-coat,`,
    `unbuttoned in the front, and a drab waistcoat with a heavy brassy`,
    `Albert chain, and a square pierced bit of metal dangling down as`,
    `an ornament. A frayed top-hat and a faded brown overcoat with a`,
    `wrinkled velvet collar lay upon a chair beside him. Altogether,`,
    `look as I would, there was nothing remarkable about the man save`,
    `his blazing red head, and the expression of extreme chagrin and`,
    `discontent upon his features.`,
    ``,
    `Sherlock Holmes' quick eye took in my occupation, and he shook`,
    `his head with a smile as he noticed my questioning glances.`,
    `"Beyond the obvious facts that he has at some time done manual`,
    `labour, that he takes snuff, that he is a Freemason, that he has`,
    `been in China, and that he has done a considerable amount of`,
    `writing lately, I can deduce nothing else."`,
    ``,
    `Mr. Jabez Wilson started up in his chair, with his forefinger`,
    `upon the paper, but his eyes upon my companion.`,
    ``,
    `"How, in the name of good-fortune, did you know all that, Mr.`,
    `Holmes?" he asked. "How did you know, for example, that I did`,
    `manual labour. It's as true as gospel, for I began as a ship's`,
    `carpenter."`,
    ``,
    `"Your hands, my dear sir. Your right hand is quite a size larger`,
    `than your left. You have worked with it, and the muscles are more`,
    `developed."`,
    ``,
    `"Well, the snuff, then, and the Freemasonry?"`,
    ``,
    `"I won't insult your intelligence by telling you how I read that,`,
    `especially as, rather against the strict rules of your order, you`,
    `use an arc-and-compass breastpin."`,
    ``,
    `"Ah, of course, I forgot that. But the writing?"`,
    ``,
    `"What else can be indicated by that right cuff so very shiny for`,
    `five inches, and the left one with the smooth patch near the`,
    `elbow where you rest it upon the desk?"`,
    ``,
    `"Well, but China?"`,
    ``,
    `"The fish that you have tattooed immediately above your right`,
    `wrist could only have been done in China. I have made a small`,
    `study of tattoo marks and have even contributed to the literature`,
    `of the subject. That trick of staining the fishes' scales of a`,
    `delicate pink is quite peculiar to China. When, in addition, I`,
    `see a Chinese coin hanging from your watch-chain, the matter`,
    `becomes even more simple."`,
    ``,
    `Mr. Jabez Wilson laughed heavily. "Well, I never!" said he. "I`,
    `thought at first that you had done something clever, but I see`,
    `that there was nothing in it, after all."`,
    ``,
    `"I begin to think, Watson," said Holmes, "that I make a mistake`,
    `in explaining. 'Omne ignotum pro magnifico,' you know, and my`,
    `poor little reputation, such as it is, will suffer shipwreck if I`,
    `am so candid. Can you not find the advertisement, Mr. Wilson?"`,
    ``,
    `"Yes, I have got it now," he answered with his thick red finger`,
    `planted halfway down the column. "Here it is. This is what began`,
    `it all. You just read it for yourself, sir."`,
    ``,
    `I took the paper from him and read as follows:`,
    ``,
    `"TO THE RED-HEADED LEAGUE: On account of the bequest of the late`,
    `Ezekiah Hopkins, of Lebanon, Pennsylvania, U. S. A., there is now`,
    `another vacancy open which entitles a member of the League to a`,
    `salary of 4 pounds a week for purely nominal services. All`,
    `red-headed men who are sound in body and mind and above the age`,
    `of twenty-one years, are eligible. Apply in person on Monday, at`,
    `eleven o'clock, to Duncan Ross, at the offices of the League, 7`,
    `Pope's Court, Fleet Street."`,
    ``,
    `"What on earth does this mean?" I ejaculated after I had twice`,
    `read over the extraordinary announcement.`,
    ``,
    `Holmes chuckled and wriggled in his chair, as was his habit when`,
    `in high spirits. "It is a little off the beaten track, isn't it?"`,
    `said he. "And now, Mr. Wilson, off you go at scratch and tell us`,
    `all about yourself, your household, and the effect which this`,
    `advertisement had upon your fortunes. You will first make a note,`,
    `Doctor, of the paper and the date."`,
    ``,
    `"It is The Morning Chronicle of April 27, 1890. Just two months`,
    `ago."`,
    ``,
    `"Very good. Now, Mr. Wilson?"`,
    ``,
    `"Well, it is just as I have been telling you, Mr. Sherlock`,
    `Holmes," said Jabez Wilson, mopping his forehead; "I have a small`,
    `pawnbroker's business at Coburg Square, near the City. It's not a`,
    `very large affair, and of late years it has not done more than`,
    `just give me a living. I used to be able to keep two assistants,`,
    `but now I only keep one; and I would have a job to pay him but`,
    `that he is willing to come for half wages so as to learn the`,
    `business."`,
    ``,
    `"What is the name of this obliging youth?" asked Sherlock Holmes.`,
    ``,
    `"His name is Vincent Spaulding, and he's not such a youth,`,
    `either. It's hard to say his age. I should not wish a smarter`,
    `assistant, Mr. Holmes; and I know very well that he could better`,
    `himself and earn twice what I am able to give him. But, after`,
    `all, if he is satisfied, why should I put ideas in his head?"`,
    ``,
    `"Why, indeed? You seem most fortunate in having an employé who`,
    `comes under the full market price. It is not a common experience`,
    `among employers in this age. I don't know that your assistant is`,
    `not as remarkable as your advertisement."`,
    ``,
    `"Oh, he has his faults, too," said Mr. Wilson. "Never was such a`,
    `fellow for photography. Snapping away with a camera when he ought`,
    `to be improving his mind, and then diving down into the cellar`,
    `like a rabbit into its hole to develop his pictures. That is his`,
    `main fault, but on the whole he's a good worker. There's no vice`,
    `in him."`,
    ``,
    `"He is still with you, I presume?"`,
    ``,
    `"Yes, sir. He and a girl of fourteen, who does a bit of simple`,
    `cooking and keeps the place clean--that's all I have in the`,
    `house, for I am a widower and never had any family. We live very`,
    `quietly, sir, the three of us; and we keep a roof over our heads`,
    `and pay our debts, if we do nothing more.`,
    ``,
    `"The first thing that put us out was that advertisement.`,
    `Spaulding, he came down into the office just this day eight`,
    `weeks, with this very paper in his hand, and he says:`,
    ``,
    `"'I wish to the Lord, Mr. Wilson, that I was a red-headed man.'`,
    ``,
    `"'Why that?' I asks.`,
    ``,
    `"'Why,' says he, 'here's another vacancy on the League of the`,
    `Red-headed Men. It's worth quite a little fortune to any man who`,
    `gets it, and I understand that there are more vacancies than`,
    `there are men, so that the trustees are at their wits' end what`,
    `to do with the money. If my hair would only change colour, here's`,
    `a nice little crib all ready for me to step into.'`,
    ``,
    `"'Why, what is it, then?' I asked. You see, Mr. Holmes, I am a`,
    `very stay-at-home man, and as my business came to me instead of`,
    `my having to go to it, I was often weeks on end without putting`,
    `my foot over the door-mat. In that way I didn't know much of what`,
    `was going on outside, and I was always glad of a bit of news.`,
    ``,
    `"'Have you never heard of the League of the Red-headed Men?' he`,
    `asked with his eyes open.`,
    ``,
    `"'Never.'`,
    ``,
    `"'Why, I wonder at that, for you are eligible yourself for one`,
    `of the vacancies.'`,
    ``,
    `"'And what are they worth?' I asked.`,
    ``,
    `"'Oh, merely a couple of hundred a year, but the work is slight,`,
    `and it need not interfere very much with one's other`,
    `occupations.'`,
    ``,
    `"Well, you can easily think that that made me prick up my ears,`,
    `for the business has not been over-good for some years, and an`,
    `extra couple of hundred would have been very handy.`,
    ``,
    `"'Tell me all about it,' said I.`,
    ``,
    `"'Well,' said he, showing me the advertisement, 'you can see for`,
    `yourself that the League has a vacancy, and there is the address`,
    `where you should apply for particulars. As far as I can make out,`,
    `the League was founded by an American millionaire, Ezekiah`,
    `Hopkins, who was very peculiar in his ways. He was himself`,
    `red-headed, and he had a great sympathy for all red-headed men;`,
    `so when he died it was found that he had left his enormous`,
    `fortune in the hands of trustees, with instructions to apply the`,
    `interest to the providing of easy berths to men whose hair is of`,
    `that colour. From all I hear it is splendid pay and very little to`,
    `do.'`,
    ``,
    `"'But,' said I, 'there would be millions of red-headed men who`,
    `would apply.'`,
    ``,
    `"'Not so many as you might think,' he answered. 'You see it is`,
    `really confined to Londoners, and to grown men. This American had`,
    `started from London when he was young, and he wanted to do the`,
    `old town a good turn. Then, again, I have heard it is no use your`,
    `applying if your hair is light red, or dark red, or anything but`,
    `real bright, blazing, fiery red. Now, if you cared to apply, Mr.`,
    `Wilson, you would just walk in; but perhaps it would hardly be`,
    `worth your while to put yourself out of the way for the sake of a`,
    `few hundred pounds.'`,
    ``,
    `"Now, it is a fact, gentlemen, as you may see for yourselves,`,
    `that my hair is of a very full and rich tint, so that it seemed`,
    `to me that if there was to be any competition in the matter I`,
    `stood as good a chance as any man that I had ever met. Vincent`,
    `Spaulding seemed to know so much about it that I thought he might`,
    `prove useful, so I just ordered him to put up the shutters for`,
    `the day and to come right away with me. He was very willing to`,
    `have a holiday, so we shut the business up and started off for`,
    `the address that was given us in the advertisement.`,
    ``,
    `"I never hope to see such a sight as that again, Mr. Holmes. From`,
    `north, south, east, and west every man who had a shade of red in`,
    `his hair had tramped into the city to answer the advertisement.`,
    `Fleet Street was choked with red-headed folk, and Pope's Court`,
    `looked like a coster's orange barrow. I should not have thought`,
    `there were so many in the whole country as were brought together`,
    `by that single advertisement. Every shade of colour they`,
    `were--straw, lemon, orange, brick, Irish-setter, liver, clay;`,
    `but, as Spaulding said, there were not many who had the real`,
    `vivid flame-coloured tint. When I saw how many were waiting, I`,
    `would have given it up in despair; but Spaulding would not hear`,
    `of it. How he did it I could not imagine, but he pushed and`,
    `pulled and butted until he got me through the crowd, and right up`,
    `to the steps which led to the office. There was a double stream`,
    `upon the stair, some going up in hope, and some coming back`,
    `dejected; but we wedged in as well as we could and soon found`,
    `ourselves in the office."`,
    ``,
    `"Your experience has been a most entertaining one," remarked`,
    `Holmes as his client paused and refreshed his memory with a huge`,
    `pinch of snuff. "Pray continue your very interesting statement."`,
    ``,
    `"There was nothing in the office but a couple of wooden chairs`,
    `and a deal table, behind which sat a small man with a head that`,
    `was even redder than mine. He said a few words to each candidate`,
    `as he came up, and then he always managed to find some fault in`,
    `them which would disqualify them. Getting a vacancy did not seem`,
    `to be such a very easy matter, after all. However, when our turn`,
    `came the little man was much more favourable to me than to any of`,
    `the others, and he closed the door as we entered, so that he`,
    `might have a private word with us.`,
    ``,
    `"'This is Mr. Jabez Wilson,' said my assistant, 'and he is`,
    `willing to fill a vacancy in the League.'`,
    ``,
    `"'And he is admirably suited for it,' the other answered. 'He has`,
    `every requirement. I cannot recall when I have seen anything so`,
    `fine.' He took a step backward, cocked his head on one side, and`,
    `gazed at my hair until I felt quite bashful. Then suddenly he`,
    `plunged forward, wrung my hand, and congratulated me warmly on my`,
    `success.`,
    ``,
    `"'It would be injustice to hesitate,' said he. 'You will,`,
    `however, I am sure, excuse me for taking an obvious precaution.'`,
    `With that he seized my hair in both his hands, and tugged until I`,
    `yelled with the pain. 'There is water in your eyes,' said he as`,
    `he released me. 'I perceive that all is as it should be. But we`,
    `have to be careful, for we have twice been deceived by wigs and`,
    `once by paint. I could tell you tales of cobbler's wax which`,
    `would disgust you with human nature.' He stepped over to the`,
    `window and shouted through it at the top of his voice that the`,
    `vacancy was filled. A groan of disappointment came up from below,`,
    `and the folk all trooped away in different directions until there`,
    `was not a red-head to be seen except my own and that of the`,
    `manager.`,
    ``,
    `"'My name,' said he, 'is Mr. Duncan Ross, and I am myself one of`,
    `the pensioners upon the fund left by our noble benefactor. Are`,
    `you a married man, Mr. Wilson? Have you a family?'`,
    ``,
    `"I answered that I had not.`,
    ``,
    `"His face fell immediately.`,
    ``,
    `"'Dear me!' he said gravely, 'that is very serious indeed! I am`,
    `sorry to hear you say that. The fund was, of course, for the`,
    `propagation and spread of the red-heads as well as for their`,
    `maintenance. It is exceedingly unfortunate that you should be a`,
    `bachelor.'`,
    ``,
    `"My face lengthened at this, Mr. Holmes, for I thought that I was`,
    `not to have the vacancy after all; but after thinking it over for`,
    `a few minutes he said that it would be all right.`,
    ``,
    `"'In the case of another,' said he, 'the objection might be`,
    `fatal, but we must stretch a point in favour of a man with such a`,
    `head of hair as yours. When shall you be able to enter upon your`,
    `new duties?'`,
    ``,
    `"'Well, it is a little awkward, for I have a business already,'`,
    `said I.`,
    ``,
    `"'Oh, never mind about that, Mr. Wilson!' said Vincent Spaulding.`,
    `'I should be able to look after that for you.'`,
    ``,
    `"'What would be the hours?' I asked.`,
    ``,
    `"'Ten to two.'`,
    ``,
    `"Now a pawnbroker's business is mostly done of an evening, Mr.`,
    `Holmes, especially Thursday and Friday evening, which is just`,
    `before pay-day; so it would suit me very well to earn a little in`,
    `the mornings. Besides, I knew that my assistant was a good man,`,
    `and that he would see to anything that turned up.`,
    ``,
    `"'That would suit me very well,' said I. 'And the pay?'`,
    ``,
    `"'Is 4 pounds a week.'`,
    ``,
    `"'And the work?'`,
    ``,
    `"'Is purely nominal.'`,
    ``,
    `"'What do you call purely nominal?'`,
    ``,
    `"'Well, you have to be in the office, or at least in the`,
    `building, the whole time. If you leave, you forfeit your whole`,
    `position forever. The will is very clear upon that point. You`,
    `don't comply with the conditions if you budge from the office`,
    `during that time.'`,
    ``,
    `"'It's only four hours a day, and I should not think of leaving,'`,
    `said I.`,
    ``,
    `"'No excuse will avail,' said Mr. Duncan Ross; 'neither sickness`,
    `nor business nor anything else. There you must stay, or you lose`,
    `your billet.'`,
    ``,
    `"'And the work?'`,
    ``,
    `"'Is to copy out the "Encyclopaedia Britannica." There is the first`,
    `volume of it in that press. You must find your own ink, pens, and`,
    `blotting-paper, but we provide this table and chair. Will you be`,
    `ready to-morrow?'`,
    ``,
    `"'Certainly,' I answered.`,
    ``,
    `"'Then, good-bye, Mr. Jabez Wilson, and let me congratulate you`,
    `once more on the important position which you have been fortunate`,
    `enough to gain.' He bowed me out of the room and I went home with`,
    `my assistant, hardly knowing what to say or do, I was so pleased`,
    `at my own good fortune.`,
    ``,
    `"Well, I thought over the matter all day, and by evening I was in`,
    `low spirits again; for I had quite persuaded myself that the`,
    `whole affair must be some great hoax or fraud, though what its`,
    `object might be I could not imagine. It seemed altogether past`,
    `belief that anyone could make such a will, or that they would pay`,
    `such a sum for doing anything so simple as copying out the`,
    `'Encyclopaedia Britannica.' Vincent Spaulding did what he could to`,
    `cheer me up, but by bedtime I had reasoned myself out of the`,
    `whole thing. However, in the morning I determined to have a look`,
    `at it anyhow, so I bought a penny bottle of ink, and with a`,
    `quill-pen, and seven sheets of foolscap paper, I started off for`,
    `Pope's Court.`,
    ``,
    `"Well, to my surprise and delight, everything was as right as`,
    `possible. The table was set out ready for me, and Mr. Duncan Ross`,
    `was there to see that I got fairly to work. He started me off`,
    `upon the letter A, and then he left me; but he would drop in from`,
    `time to time to see that all was right with me. At two o'clock he`,
    `bade me good-day, complimented me upon the amount that I had`,
    `written, and locked the door of the office after me.`,
    ``,
    `"This went on day after day, Mr. Holmes, and on Saturday the`,
    `manager came in and planked down four golden sovereigns for my`,
    `week's work. It was the same next week, and the same the week`,
    `after. Every morning I was there at ten, and every afternoon I`,
    `left at two. By degrees Mr. Duncan Ross took to coming in only`,
    `once of a morning, and then, after a time, he did not come in at`,
    `all. Still, of course, I never dared to leave the room for an`,
    `instant, for I was not sure when he might come, and the billet`,
    `was such a good one, and suited me so well, that I would not risk`,
    `the loss of it.`,
    ``,
    `"Eight weeks passed away like this, and I had written about`,
    `Abbots and Archery and Armour and Architecture and Attica, and`,
    `hoped with diligence that I might get on to the B's before very`,
    `long. It cost me something in foolscap, and I had pretty nearly`,
    `filled a shelf with my writings. And then suddenly the whole`,
    `business came to an end."`,
    ``,
    `"To an end?"`,
    ``,
    `"Yes, sir. And no later than this morning. I went to my work as`,
    `usual at ten o'clock, but the door was shut and locked, with a`,
    `little square of cardboard hammered on to the middle of the`,
    `panel with a tack. Here it is, and you can read for yourself."`,
]);
